services:
  - type: web
    name: thedigitaltrading-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_PORT
        value: 465
      - key: EMAIL_SECURE
        value: true
      - key: EMAIL_FROM
        sync: false
      - key: CORS_ORIGIN
        value: https://www.thedigitaltrading.com,https://thedigitaltrading.com,https://api.thedigitaltrading.com
      - key: FRONTEND_URL
        value: https://www.thedigitaltrading.com

  - type: web
    name: thedigitaltrading-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: REACT_APP_API_URL
        value: https://api.thedigitaltrading.com
      - key: REACT_APP_API_BASE_URL
        value: https://api.thedigitaltrading.com
      - key: REACT_APP_SOCKET_URL
        value: wss://api.thedigitaltrading.com
      - key: REACT_APP_WS_BASE_URL
        value: wss://api.thedigitaltrading.com
      - key: REACT_APP_FRONTEND_URL
        value: https://www.thedigitaltrading.com