services:
  - type: web
    name: thedigitaltrading-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: REACT_APP_API_URL
        sync: false

  - type: web
    name: thedigitaltrading-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000